#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Last command is not cut b/c it can create a newline for some reason. I don't really know.
ACTIVE_WINDOW_NAME=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_NAME | cut -d '"' -f 2 | awk '{print substr($0,0,50)}')
ACTIVE_WINDOW_CLASS=$(xprop -id $(xprop -root _NET_ACTIVE_WINDOW | cut -d ' ' -f 5) WM_CLASS | cut -d '"' -f 2 | awk '{print substr($0,0,50)}')
USER_TERM="sakura"

dump_tmux_info() {
	tmux list-panes -a -F "#{session_activity} #{session_name} #{window_index} #{window_index}:#{window_name}#F"
}
active_tmux_windows() {
	dump_tmux_info | sort -k1,1nr -u -k3 -u -k2 -u | awk '
		NR == 1 {max = $1; maxv = sep = ""} 
		$1 == max {maxv = maxv sep $NF; sep = " / "} 
		END {print maxv}
	'
}
# HELP! calling active_tmux_windows won't call dump_tmux_info from source
source i3-tmux #not using.
#active_tmux_windows
tmux_windows=$(active_tmux_windows)

if [[ "${ACTIVE_WINDOW_NAME}" != "" ]]; then
	if [[ "${ACTIVE_WINDOW_CLASS}" == "${USER_TERM}" && "${tmux_windows}" != "" ]]; then
		echo "${tmux_windows}"
		# echo "${tmux_windows}"
		echo ""
	else
		echo "${ACTIVE_WINDOW_NAME}"
		# echo "${ACTIVE_WINDOW_NAME}"
		echo ""
	fi
fi
